const Template = require('../../../models/Template');
const User = require('../../../models/User');
const { handleAsyncOperation, formatSuccessResponse, formatErrorResponse, isValidObjectId } = require('../../../utils/templateHelpers');
const logger = require('../../../utils/logger');

/**
 * AI Users Controller
 * Handles CRUD operations for AI user-related fields
 */

/**
 * Get AI user data for a template
 */
const getUserData = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { templateId } = req.params;
        
        const template = await Template.findById(templateId)
            .select('generatedByUser generatedByUserUid')
            .populate('generatedByUser', 'name email profileImage');
        
        if (!template) {
            return res.status(404).json(formatErrorResponse(
                'TEMPLATE_NOT_FOUND',
                'Template not found',
                'templateId',
                templateId
            ));
        }
        
        logger.info(`Retrieved AI user data for template: ${templateId}`);
        
        return res.json(formatSuccessResponse({
            templateId: template._id,
            generatedByUser: template.generatedByUser,
            generatedByUserUid: template.generatedByUserUid
        }));
    });
};

/**
 * Update AI user data for a template
 */
const updateUserData = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { templateId } = req.params;
        const { generatedByUser, generatedByUserUid } = req.body;
        
        const updateData = {};
        const modifiedFields = [];
        
        if (generatedByUser !== undefined) {
            if (generatedByUser && !isValidObjectId(generatedByUser)) {
                return res.status(400).json(formatErrorResponse(
                    'INVALID_USER_ID',
                    'Generated by user must be a valid ObjectId',
                    'generatedByUser',
                    generatedByUser
                ));
            }
            updateData.generatedByUser = generatedByUser;
            modifiedFields.push('generatedByUser');
        }
        
        if (generatedByUserUid !== undefined) {
            // Firebase UID validation
            if (generatedByUserUid && !/^[a-zA-Z0-9_-]{10,128}$/.test(generatedByUserUid)) {
                return res.status(400).json(formatErrorResponse(
                    'INVALID_FIREBASE_UID',
                    'Generated by user UID must be a valid Firebase UID',
                    'generatedByUserUid',
                    generatedByUserUid
                ));
            }
            updateData.generatedByUserUid = generatedByUserUid;
            modifiedFields.push('generatedByUserUid');
        }
        
        if (Object.keys(updateData).length === 0) {
            return res.status(400).json(formatErrorResponse(
                'NO_FIELDS_TO_UPDATE',
                'No valid fields provided for update'
            ));
        }
        
        const template = await Template.findByIdAndUpdate(
            templateId,
            { $set: updateData },
            { new: true, runValidators: true }
        ).select('generatedByUser generatedByUserUid').populate('generatedByUser', 'name email profileImage');
        
        if (!template) {
            return res.status(404).json(formatErrorResponse(
                'TEMPLATE_NOT_FOUND',
                'Template not found',
                'templateId',
                templateId
            ));
        }
        
        logger.info(`Updated AI user data for template: ${templateId}`, { modifiedFields });
        
        return res.json(formatSuccessResponse({
            templateId: template._id,
            generatedByUser: template.generatedByUser,
            generatedByUserUid: template.generatedByUserUid,
            modifiedFields
        }));
    });
};

/**
 * Clear AI user data for a template
 */
const clearUserData = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { templateId } = req.params;
        
        const template = await Template.findByIdAndUpdate(
            templateId,
            { 
                $set: {
                    generatedByUser: null,
                    generatedByUserUid: null
                }
            },
            { new: true, runValidators: true }
        ).select('generatedByUser generatedByUserUid');
        
        if (!template) {
            return res.status(404).json(formatErrorResponse(
                'TEMPLATE_NOT_FOUND',
                'Template not found',
                'templateId',
                templateId
            ));
        }
        
        logger.info(`Cleared AI user data for template: ${templateId}`);
        
        return res.json(formatSuccessResponse({
            templateId: template._id,
            message: 'AI user data cleared successfully',
            clearedFields: ['generatedByUser', 'generatedByUserUid']
        }));
    });
};

/**
 * Update generatedByUser field
 */
const updateGeneratedByUser = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { templateId } = req.params;
        const { userId } = req.body;
        
        if (userId && !isValidObjectId(userId)) {
            return res.status(400).json(formatErrorResponse(
                'INVALID_USER_ID',
                'User ID must be a valid ObjectId',
                'userId',
                userId
            ));
        }
        
        // Verify user exists if userId is provided
        if (userId) {
            const userExists = await User.findById(userId);
            if (!userExists) {
                return res.status(404).json(formatErrorResponse(
                    'USER_NOT_FOUND',
                    'User not found',
                    'userId',
                    userId
                ));
            }
        }
        
        const template = await Template.findByIdAndUpdate(
            templateId,
            { $set: { generatedByUser: userId } },
            { new: true, runValidators: true }
        ).select('generatedByUser').populate('generatedByUser', 'name email profileImage');
        
        if (!template) {
            return res.status(404).json(formatErrorResponse(
                'TEMPLATE_NOT_FOUND',
                'Template not found',
                'templateId',
                templateId
            ));
        }
        
        logger.info(`Updated generatedByUser for template: ${templateId} to ${userId}`);
        
        return res.json(formatSuccessResponse({
            templateId: template._id,
            generatedByUser: template.generatedByUser,
            modifiedFields: ['generatedByUser']
        }));
    });
};

/**
 * Update generatedByUserUid field
 */
const updateGeneratedByUserUid = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { templateId } = req.params;
        const { uid } = req.body;
        
        if (uid && !/^[a-zA-Z0-9_-]{10,128}$/.test(uid)) {
            return res.status(400).json(formatErrorResponse(
                'INVALID_FIREBASE_UID',
                'UID must be a valid Firebase UID',
                'uid',
                uid
            ));
        }
        
        const template = await Template.findByIdAndUpdate(
            templateId,
            { $set: { generatedByUserUid: uid } },
            { new: true, runValidators: true }
        ).select('generatedByUserUid');
        
        if (!template) {
            return res.status(404).json(formatErrorResponse(
                'TEMPLATE_NOT_FOUND',
                'Template not found',
                'templateId',
                templateId
            ));
        }
        
        logger.info(`Updated generatedByUserUid for template: ${templateId} to ${uid}`);
        
        return res.json(formatSuccessResponse({
            templateId: template._id,
            generatedByUserUid: template.generatedByUserUid,
            modifiedFields: ['generatedByUserUid']
        }));
    });
};

/**
 * Get templates generated by a specific user (ObjectId)
 */
const getTemplatesByUser = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { userId } = req.params;
        const { page = 1, limit = 20 } = req.query;
        
        if (!isValidObjectId(userId)) {
            return res.status(400).json(formatErrorResponse(
                'INVALID_USER_ID',
                'User ID must be a valid ObjectId',
                'userId',
                userId
            ));
        }
        
        const skip = (page - 1) * limit;
        
        const templates = await Template.find({ generatedByUser: userId })
            .select('title category isAIGenerated aiModel aiStyle aiPrompt createdAt')
            .skip(skip)
            .limit(parseInt(limit))
            .sort({ createdAt: -1 });
        
        const total = await Template.countDocuments({ generatedByUser: userId });
        
        // Get user info
        const user = await User.findById(userId).select('name email profileImage');
        
        logger.info(`Retrieved ${templates.length} templates generated by user: ${userId}`);
        
        return res.json(formatSuccessResponse({
            templates,
            user,
            pagination: {
                page: parseInt(page),
                limit: parseInt(limit),
                total,
                pages: Math.ceil(total / limit)
            },
            filter: { userId }
        }));
    });
};

/**
 * Get templates generated by a specific user (Firebase UID)
 */
const getTemplatesByUserUid = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { uid } = req.params;
        const { page = 1, limit = 20 } = req.query;
        
        if (!/^[a-zA-Z0-9_-]{10,128}$/.test(uid)) {
            return res.status(400).json(formatErrorResponse(
                'INVALID_FIREBASE_UID',
                'UID must be a valid Firebase UID',
                'uid',
                uid
            ));
        }
        
        const skip = (page - 1) * limit;
        
        const templates = await Template.find({ generatedByUserUid: uid })
            .select('title category isAIGenerated aiModel aiStyle aiPrompt createdAt')
            .skip(skip)
            .limit(parseInt(limit))
            .sort({ createdAt: -1 });
        
        const total = await Template.countDocuments({ generatedByUserUid: uid });
        
        logger.info(`Retrieved ${templates.length} templates generated by user UID: ${uid}`);
        
        return res.json(formatSuccessResponse({
            templates,
            pagination: {
                page: parseInt(page),
                limit: parseInt(limit),
                total,
                pages: Math.ceil(total / limit)
            },
            filter: { uid }
        }));
    });
};

/**
 * Get AI generation statistics for a user
 */
const getUserGenerationStats = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { userId } = req.params;
        
        if (!isValidObjectId(userId)) {
            return res.status(400).json(formatErrorResponse(
                'INVALID_USER_ID',
                'User ID must be a valid ObjectId',
                'userId',
                userId
            ));
        }
        
        const [
            totalGenerated,
            modelStats,
            styleStats,
            stageStats
        ] = await Promise.all([
            Template.countDocuments({ generatedByUser: userId, isAIGenerated: true }),
            Template.aggregate([
                { $match: { generatedByUser: userId, isAIGenerated: true, aiModel: { $ne: '' } } },
                { $group: { _id: '$aiModel', count: { $sum: 1 } } },
                { $sort: { count: -1 } }
            ]),
            Template.aggregate([
                { $match: { generatedByUser: userId, isAIGenerated: true, aiStyle: { $ne: '' } } },
                { $group: { _id: '$aiStyle', count: { $sum: 1 } } },
                { $sort: { count: -1 } }
            ]),
            Template.aggregate([
                { $match: { generatedByUser: userId, isAIGenerated: true } },
                { $group: { _id: '$aiGenerationStage', count: { $sum: 1 } } }
            ])
        ]);
        
        const user = await User.findById(userId).select('name email profileImage');
        
        logger.info(`Retrieved AI generation statistics for user: ${userId}`);
        
        return res.json(formatSuccessResponse({
            user,
            totalGenerated,
            modelStats,
            styleStats,
            stageStats,
            generatedAt: new Date().toISOString()
        }));
    });
};

/**
 * Get AI generation statistics for a user by Firebase UID
 */
const getUserGenerationStatsByUid = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { uid } = req.params;
        
        if (!/^[a-zA-Z0-9_-]{10,128}$/.test(uid)) {
            return res.status(400).json(formatErrorResponse(
                'INVALID_FIREBASE_UID',
                'UID must be a valid Firebase UID',
                'uid',
                uid
            ));
        }
        
        const [
            totalGenerated,
            modelStats,
            styleStats,
            stageStats
        ] = await Promise.all([
            Template.countDocuments({ generatedByUserUid: uid, isAIGenerated: true }),
            Template.aggregate([
                { $match: { generatedByUserUid: uid, isAIGenerated: true, aiModel: { $ne: '' } } },
                { $group: { _id: '$aiModel', count: { $sum: 1 } } },
                { $sort: { count: -1 } }
            ]),
            Template.aggregate([
                { $match: { generatedByUserUid: uid, isAIGenerated: true, aiStyle: { $ne: '' } } },
                { $group: { _id: '$aiStyle', count: { $sum: 1 } } },
                { $sort: { count: -1 } }
            ]),
            Template.aggregate([
                { $match: { generatedByUserUid: uid, isAIGenerated: true } },
                { $group: { _id: '$aiGenerationStage', count: { $sum: 1 } } }
            ])
        ]);
        
        logger.info(`Retrieved AI generation statistics for user UID: ${uid}`);
        
        return res.json(formatSuccessResponse({
            uid,
            totalGenerated,
            modelStats,
            styleStats,
            stageStats,
            generatedAt: new Date().toISOString()
        }));
    });
};

/**
 * Batch assign generated-by-user for multiple templates
 */
const batchAssignUser = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { templateIds, userId, uid } = req.body;
        
        if (!templateIds || !Array.isArray(templateIds) || templateIds.length === 0) {
            return res.status(400).json(formatErrorResponse(
                'INVALID_TEMPLATE_IDS',
                'Template IDs array is required'
            ));
        }
        
        const updateData = {};
        
        if (userId !== undefined) {
            if (userId && !isValidObjectId(userId)) {
                return res.status(400).json(formatErrorResponse(
                    'INVALID_USER_ID',
                    'User ID must be a valid ObjectId',
                    'userId',
                    userId
                ));
            }
            updateData.generatedByUser = userId;
        }
        
        if (uid !== undefined) {
            if (uid && !/^[a-zA-Z0-9_-]{10,128}$/.test(uid)) {
                return res.status(400).json(formatErrorResponse(
                    'INVALID_FIREBASE_UID',
                    'UID must be a valid Firebase UID',
                    'uid',
                    uid
                ));
            }
            updateData.generatedByUserUid = uid;
        }
        
        if (Object.keys(updateData).length === 0) {
            return res.status(400).json(formatErrorResponse(
                'NO_UPDATE_DATA',
                'Either userId or uid must be provided'
            ));
        }
        
        const result = await Template.updateMany(
            { _id: { $in: templateIds } },
            { $set: updateData },
            { runValidators: true }
        );
        
        logger.info(`Batch assigned user for ${result.modifiedCount} templates`);
        
        return res.json(formatSuccessResponse({
            message: 'Batch user assignment completed',
            matchedCount: result.matchedCount,
            modifiedCount: result.modifiedCount,
            templateIds,
            updateData
        }));
    });
};

/**
 * Get overall user generation statistics
 */
const getOverallUserStats = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const [
            totalUsersGenerated,
            topGeneratorsByObjectId,
            topGeneratorsByUid,
            totalAITemplates
        ] = await Promise.all([
            Template.distinct('generatedByUser', { isAIGenerated: true, generatedByUser: { $ne: null } }),
            Template.aggregate([
                { $match: { isAIGenerated: true, generatedByUser: { $ne: null } } },
                { $group: { _id: '$generatedByUser', count: { $sum: 1 } } },
                { $sort: { count: -1 } },
                { $limit: 10 },
                { 
                    $lookup: {
                        from: 'users',
                        localField: '_id',
                        foreignField: '_id',
                        as: 'user'
                    }
                },
                { $unwind: '$user' },
                {
                    $project: {
                        userId: '$_id',
                        count: 1,
                        userName: '$user.name',
                        userEmail: '$user.email'
                    }
                }
            ]),
            Template.aggregate([
                { $match: { isAIGenerated: true, generatedByUserUid: { $ne: null } } },
                { $group: { _id: '$generatedByUserUid', count: { $sum: 1 } } },
                { $sort: { count: -1 } },
                { $limit: 10 }
            ]),
            Template.countDocuments({ isAIGenerated: true })
        ]);
        
        logger.info('Retrieved overall user generation statistics');
        
        return res.json(formatSuccessResponse({
            totalUsersGenerated: totalUsersGenerated.length,
            totalAITemplates,
            topGeneratorsByObjectId,
            topGeneratorsByUid,
            generatedAt: new Date().toISOString()
        }));
    });
};

/**
 * Get top AI template generators
 */
const getTopGenerators = async (req, res) => {
    await handleAsyncOperation(res, async () => {
        const { limit = 10 } = req.params;
        const limitNum = parseInt(limit);
        
        if (isNaN(limitNum) || limitNum < 1 || limitNum > 100) {
            return res.status(400).json(formatErrorResponse(
                'INVALID_LIMIT',
                'Limit must be a number between 1 and 100',
                'limit',
                limit
            ));
        }
        
        const topGenerators = await Template.aggregate([
            { $match: { isAIGenerated: true, generatedByUser: { $ne: null } } },
            { $group: { _id: '$generatedByUser', count: { $sum: 1 } } },
            { $sort: { count: -1 } },
            { $limit: limitNum },
            { 
                $lookup: {
                    from: 'users',
                    localField: '_id',
                    foreignField: '_id',
                    as: 'user'
                }
            },
            { $unwind: '$user' },
            {
                $project: {
                    userId: '$_id',
                    count: 1,
                    userName: '$user.name',
                    userEmail: '$user.email',
                    userProfileImage: '$user.profileImage'
                }
            }
        ]);
        
        logger.info(`Retrieved top ${limitNum} AI template generators`);
        
        return res.json(formatSuccessResponse({
            topGenerators,
            limit: limitNum,
            generatedAt: new Date().toISOString()
        }));
    });
};

module.exports = {
    getUserData,
    updateUserData,
    clearUserData,
    updateGeneratedByUser,
    updateGeneratedByUserUid,
    getTemplatesByUser,
    getTemplatesByUserUid,
    getUserGenerationStats,
    getUserGenerationStatsByUid,
    batchAssignUser,
    getOverallUserStats,
    getTopGenerators
};
