const express = require('express');
const router = express.Router();
const { validateTemplateId, validateTemplateExists, validateAIMetadata } = require('../../../middleware/templateValidators');
const usersController = require('../../../controllers/templates/ai/usersController');
const logger = require('../../../utils/logger');

/**
 * AI Users Routes
 * CRUD operations for AI user-related fields:
 * - generatedByUser (ObjectId, ref: 'User')
 * - generatedByUserUid (String, Firebase UID)
 */

/**
 * @route GET /api/templates/ai/users/:templateId
 * @desc Get AI user data for a template
 * @access Public
 */
router.get('/:templateId', 
    validateTemplateId, 
    validateTemplateExists, 
    usersController.getUserData
);

/**
 * @route PUT /api/templates/ai/users/:templateId
 * @desc Update AI user data for a template
 * @access Public
 */
router.put('/:templateId', 
    validateTemplateId, 
    validateTemplateExists, 
    validateAIMetadata, 
    usersController.updateUserData
);

/**
 * @route DELETE /api/templates/ai/users/:templateId
 * @desc Clear AI user data for a template
 * @access Public
 */
router.delete('/:templateId', 
    validateTemplateId, 
    validateTemplateExists, 
    usersController.clearUserData
);

/**
 * @route PUT /api/templates/ai/users/:templateId/generated-by-user
 * @desc Update generatedByUser field
 * @access Public
 */
router.put('/:templateId/generated-by-user', 
    validateTemplateId, 
    validateTemplateExists, 
    usersController.updateGeneratedByUser
);

/**
 * @route PUT /api/templates/ai/users/:templateId/generated-by-uid
 * @desc Update generatedByUserUid field
 * @access Public
 */
router.put('/:templateId/generated-by-uid', 
    validateTemplateId, 
    validateTemplateExists, 
    usersController.updateGeneratedByUserUid
);

/**
 * @route GET /api/templates/ai/users/generated-by/:userId
 * @desc Get templates generated by a specific user (ObjectId)
 * @access Public
 */
router.get('/generated-by/:userId', 
    usersController.getTemplatesByUser
);

/**
 * @route GET /api/templates/ai/users/generated-by-uid/:uid
 * @desc Get templates generated by a specific user (Firebase UID)
 * @access Public
 */
router.get('/generated-by-uid/:uid', 
    usersController.getTemplatesByUserUid
);

/**
 * @route GET /api/templates/ai/users/:userId/stats
 * @desc Get AI generation statistics for a user
 * @access Public
 */
router.get('/:userId/stats', 
    usersController.getUserGenerationStats
);

/**
 * @route GET /api/templates/ai/users/uid/:uid/stats
 * @desc Get AI generation statistics for a user by Firebase UID
 * @access Public
 */
router.get('/uid/:uid/stats', 
    usersController.getUserGenerationStatsByUid
);

/**
 * @route POST /api/templates/ai/users/batch/assign
 * @desc Batch assign generated-by-user for multiple templates
 * @access Public
 */
router.post('/batch/assign', 
    usersController.batchAssignUser
);

/**
 * @route GET /api/templates/ai/users/stats/overview
 * @desc Get overall user generation statistics
 * @access Public
 */
router.get('/stats/overview', 
    usersController.getOverallUserStats
);

/**
 * @route GET /api/templates/ai/users/top-generators/:limit
 * @desc Get top AI template generators
 * @access Public
 */
router.get('/top-generators/:limit', 
    usersController.getTopGenerators
);

module.exports = router; 